const fs = require('fs')
const path = require('path')

const B2 = 'C:/Users/Helbert/Documents/Verdent/barbeza2'
const B1 = 'C:/Users/Helbert/Documents/Verdent/barbeza-barbearia'

// ─── content.ts (UTF-8 correto com todos acentos) ────────────────────────────
const content = [
  "import type { Service, GalleryItem, Testimonial, Stat, BusinessHours, SpaceRoom } from '@/types'",
  "",
  "export const BUSINESS = {",
  "  name: 'BARBEZA BARBEARIA',",
  "  slogan: 'Experi\u00eancia Masculina',",
  "  tagline: 'Corte, barba e atendimento diferenciado',",
  "  address: 'Av. Selim Jos\u00e9 de Sales, Beth\u00e2nia',",
  "  city: 'Ipatinga \u2014 MG',",
  "  fullAddress: 'Avenida Selim Jos\u00e9 de Sales, Beth\u00e2nia, Ipatinga - MG',",
  "  phone: '(31) 9831-3831',",
  "  whatsapp: '5531983143831',",
  "  instagram: 'barbezabarbearia',",
  "  instagramUrl: 'https://www.instagram.com/barbezabarbearia',",
  "  inbarberUrl: 'https://chat.inbarberapp.com/AGENDABARBEZA',",
  "  googleMapsUrl: 'https://maps.google.com/maps?q=Avenida+Selim+Jose+de+Sales+Bethania+Ipatinga+MG&output=embed',",
  "  googleMapsLink: 'https://maps.google.com/?q=Avenida+Selim+Jose+de+Sales+Bethania+Ipatinga+MG',",
  "} as const",
  "",
  "export const SERVICES: Service[] = [",
  "  { id: 'corte',  name: 'Corte',              price: 50,  duration: '45 min',   icon: 'Scissors', description: 'Corte masculino personalizado com t\u00e9cnica e precis\u00e3o. Lavagem e finaliza\u00e7\u00e3o inclu\u00eddas.' },",
  "  { id: 'barba',  name: 'Barba',              price: 30,  duration: '30 min',   icon: 'Smile',    description: 'Modelagem e aparagem de barba com navalha e produtos premium. Toalha quente e hidrata\u00e7\u00e3o.' },",
  "  { id: 'combo',  name: 'Combo',              price: 70,  duration: '1h 15min', icon: 'Sparkles', description: 'Corte + Barba completos. A experi\u00eancia masculina completa com desconto especial.', featured: true },",
  "  { id: 'noivo',  name: 'Making Of do Noivo', price: 150, duration: '2h',       icon: 'Crown',    description: 'Prepara\u00e7\u00e3o completa para o grande dia. Corte, barba, hidrata\u00e7\u00e3o e tratamento premium.', premium: true },",
  "]",
  "",
  "export const HOURS: BusinessHours = {",
  "  monday:    { label: 'Segunda-feira', open: '09:00', close: '19:00', active: true  },",
  "  tuesday:   { label: 'Ter\u00e7a-feira',   open: '09:00', close: '19:00', active: true  },",
  "  wednesday: { label: 'Quarta-feira',  open: '09:00', close: '19:00', active: true  },",
  "  thursday:  { label: 'Quinta-feira',  open: '09:00', close: '19:00', active: true  },",
  "  friday:    { label: 'Sexta-feira',   open: '09:00', close: '20:00', active: true  },",
  "  saturday:  { label: 'S\u00e1bado',        open: '08:00', close: '18:00', active: true  },",
  "  sunday:    { label: 'Domingo',       open: '',      close: '',      active: false },",
  "}",
  "",
  "export const GALLERY: GalleryItem[] = [",
  "  { id: '1', file: '/assets/images/gallery-01.jpg', alt: 'Corte masculino degr\u00ea',     category: 'cortes'   },",
  "  { id: '2', file: '/assets/images/gallery-02.jpg', alt: 'Barba modelada com navalha',  category: 'barbas'   },",
  "  { id: '3', file: '/assets/images/gallery-03.jpg', alt: 'Interior da barbearia',       category: 'ambiente' },",
  "  { id: '4', file: '/assets/images/gallery-04.jpg', alt: 'Corte social cl\u00e1ssico',      category: 'cortes'   },",
  "  { id: '5', file: '/assets/images/gallery-05.jpg', alt: 'Cadeiras de barbeiro',        category: 'ambiente' },",
  "  { id: '6', file: '/assets/images/gallery-06.jpg', alt: 'Barba completa e estilizada', category: 'barbas'   },",
  "]",
  "",
  "export const TESTIMONIALS: Testimonial[] = [",
  "  { id: '1', name: 'Rafael Mendes',  text: 'Melhor barbearia de Ipatinga! Atendimento impec\u00e1vel, ambiente incr\u00edvel e o corte ficou perfeito. N\u00e3o troco por nada.', rating: 5, service: 'Combo' },",
  "  { id: '2', name: 'Lucas Ferreira', text: 'Fiz o Making Of do Noivo e sa\u00ed de l\u00e1 me sentindo o cara mais bem cuidado do mundo. Recomendo 100%!', rating: 5, service: 'Making Of do Noivo' },",
  "  { id: '3', name: 'Bruno Alves',    text: 'Frequento toda semana. O cuidado com cada detalhe \u00e9 o que diferencia a Barbeza. Ambiente top demais.', rating: 5, service: 'Corte + Barba' },",
  "  { id: '4', name: 'Diego Costa',    text: 'Profissionalismo e qualidade acima da m\u00e9dia. A barba ficou impec\u00e1vel, melhor da cidade.', rating: 5, service: 'Barba' },",
  "]",
  "",
  "export const STATS: Stat[] = [",
  "  { label: 'Seguidores',          value: 1199, suffix: '+',  prefix: ''   },",
  "  { label: 'Clientes Atendidos',  value: 500,  suffix: '+',  prefix: ''   },",
  "  { label: 'Avalia\u00e7\u00e3o',           value: 5,    suffix: '.0', prefix: '\u2605 ' },",
  "  { label: 'Anos de Experi\u00eancia', value: 3,    suffix: '+',  prefix: ''   },",
  "]",
  "",
  "export const SPACE_ROOMS: SpaceRoom[] = [",
  "  { id: 'area-corte', label: '\u00c1rea de Corte', description: 'Esta\u00e7\u00f5es de trabalho premium com cadeiras de barbeiro tradicionais e ilumina\u00e7\u00e3o profissional para cada detalhe do seu estilo.', image: '/assets/renders/render-01.jpg', badge: 'NOVO ESPA\u00c7O'  },",
  "  { id: 'recepcao',   label: 'Recep\u00e7\u00e3o',        description: 'Ambiente acolhedor onde a experi\u00eancia come\u00e7a. Design sofisticado em tons escuros e dourados que define o padr\u00e3o Barbeza.',      image: '/assets/renders/render-02.jpg', badge: 'EM BREVE'     },",
  "  { id: 'sala-vip',   label: 'Sala VIP',         description: 'Espa\u00e7o exclusivo para atendimentos especiais como o Making Of do Noivo. Privacidade e luxo para o seu momento.',                image: '/assets/renders/render-03.jpg', badge: 'EXCLUSIVO'    },",
  "]",
].join('\n')

// ─── Navbar barbeza2: logo SEMPRE visivel (discreta no hero) ──────────────────
const navbarB2 = [
  'import { useState } from "react"',
  'import { useScrollY, useScrollProgress } from "@/hooks/useScrollAnimation"',
  'import { BUSINESS } from "@/data/content"',
  'import { Button } from "@/components/ui/Button"',
  'import { Menu, X } from "lucide-react"',
  '',
  'const NAV_LINKS = [',
  '  { label: "Servi\u00e7os",    href: "#servicos" },',
  '  { label: "Espa\u00e7o",      href: "#espaco" },',
  '  { label: "Galeria",      href: "#galeria" },',
  '  { label: "Depoimentos", href: "#depoimentos" },',
  '  { label: "Contato",     href: "#contato" },',
  ']',
  '',
  'export function Navbar() {',
  '  const scrollY = useScrollY()',
  '  const progress = useScrollProgress()',
  '  const [open, setOpen] = useState(false)',
  '  const scrolled = scrollY > 80',
  '',
  '  return (',
  '    <>',
  '      <div',
  '        className="fixed top-0 left-0 z-[100] h-[2px] transition-all duration-100"',
  '        style={{ width: `${progress * 100}%`, background: "linear-gradient(90deg,#3D5A3D,#8B8555)" }}',
  '      />',
  '',
  '      <nav className={`fixed top-0 left-0 right-0 z-50 transition-all duration-500 ${',
  '        scrolled',
  '          ? "bg-natural/96 backdrop-blur-md shadow-[0_2px_16px_rgba(61,90,61,0.12)] border-b border-natural-border"',
  '          : "bg-transparent"',
  '      }`}>',
  '        <div className="max-w-7xl mx-auto px-6 md:px-10 flex items-center justify-between h-16 md:h-18">',
  '',
  '          {/* Logo sempre vis\u00edvel: discreta no hero, destacada ao rolar */}',
  '          <a href="/" className="flex items-center gap-2 group transition-all duration-300">',
  '            <div className={`w-8 h-8 rounded-full flex items-center justify-center overflow-hidden transition-all duration-300 ${scrolled ? "bg-forest" : "bg-white/15 backdrop-blur-sm border border-white/25"}`}>',
  '              <img src="/assets/logo/logo.png" alt="B" className="w-7 h-7 object-contain" />',
  '            </div>',
  '            <div>',
  '              <p className={`font-raleway text-sm font-black tracking-[0.2em] leading-none transition-colors duration-300 ${scrolled ? "text-forest" : "text-white"}`}>BARBEZA</p>',
  '              <p className={`font-inter text-[9px] tracking-widest uppercase transition-colors duration-300 ${scrolled ? "text-ink-dim" : "text-white/60"}`}>Barbearia</p>',
  '            </div>',
  '          </a>',
  '',
  '          {/* Links */}',
  '          <ul className="hidden md:flex items-center gap-8">',
  '            {NAV_LINKS.map(l => (',
  '              <li key={l.href}>',
  '                <a href={l.href} className={`font-inter text-xs tracking-wider uppercase transition-colors duration-200 ${',
  '                  scrolled ? "text-ink-muted hover:text-forest" : "text-white/75 hover:text-white"',
  '                }`}>',
  '                  {l.label}',
  '                </a>',
  '              </li>',
  '            ))}',
  '          </ul>',
  '',
  '          <div className="hidden md:block">',
  '            <Button',
  '              href={BUSINESS.inbarberUrl}',
  '              target="_blank"',
  '              size="sm"',
  '              variant={scrolled ? "primary" : "outline"}',
  '              className={scrolled ? "" : "border-white/60 text-white hover:bg-white hover:text-forest"}',
  '            >',
  '              AGENDAR',
  '            </Button>',
  '          </div>',
  '',
  '          <button',
  '            className={`md:hidden p-2 transition-colors ${scrolled ? "text-ink" : "text-white"}`}',
  '            onClick={() => setOpen(true)}',
  '          >',
  '            <Menu size={22} />',
  '          </button>',
  '        </div>',
  '      </nav>',
  '',
  '      {open && (',
  '        <div className="fixed inset-0 z-[200] bg-natural/98 backdrop-blur-xl flex flex-col">',
  '          <div className="flex items-center justify-between px-6 h-16 border-b border-natural-border">',
  '            <div className="flex items-center gap-2">',
  '              <div className="w-8 h-8 rounded-full bg-forest flex items-center justify-center overflow-hidden">',
  '                <img src="/assets/logo/logo.png" alt="" className="w-7 h-7 object-contain" />',
  '              </div>',
  '              <p className="font-raleway text-forest text-sm font-black tracking-widest">BARBEZA</p>',
  '            </div>',
  '            <button className="text-ink p-2" onClick={() => setOpen(false)}><X size={22} /></button>',
  '          </div>',
  '          <div className="flex-1 flex flex-col items-center justify-center gap-7">',
  '            {NAV_LINKS.map(l => (',
  '              <a key={l.href} href={l.href} onClick={() => setOpen(false)}',
  '                className="font-raleway text-3xl text-ink font-black hover:text-forest tracking-widest transition-colors uppercase">',
  '                {l.label}',
  '              </a>',
  '            ))}',
  '            <div className="mt-4">',
  '              <Button href={BUSINESS.inbarberUrl} target="_blank" size="lg" onClick={() => setOpen(false)}>AGENDAR</Button>',
  '            </div>',
  '          </div>',
  '          <div className="pb-8 flex items-center justify-center gap-3">',
  '            <div className="h-px w-10 bg-forest/20" />',
  '            <span className="font-inter text-xs text-ink-dim">@barbezabarbearia</span>',
  '            <div className="h-px w-10 bg-forest/20" />',
  '          </div>',
  '        </div>',
  '      )}',
  '    </>',
  '  )',
  '}',
].join('\n')

// ─── ServicesSection ──────────────────────────────────────────────────────────
const services = [
  'import { Scissors, Smile, Sparkles, Crown, type LucideProps } from "lucide-react"',
  'import { type ForwardRefExoticComponent, type RefAttributes } from "react"',
  'import { SERVICES, BUSINESS } from "@/data/content"',
  'import { Button } from "@/components/ui/Button"',
  'import { GoldDivider } from "@/components/ui/GoldDivider"',
  'import { useScrollAnimation } from "@/hooks/useScrollAnimation"',
  'type LucideIcon = ForwardRefExoticComponent<LucideProps & RefAttributes<SVGSVGElement>>',
  'const ICONS: Record<string,LucideIcon> = { Scissors, Smile, Sparkles, Crown }',
  'export function ServicesSection() {',
  '  const { ref, isVisible } = useScrollAnimation(0.1)',
  '  return (',
  '    <section id="servicos" className="section-padding bg-natural">',
  '      <div className="max-w-7xl mx-auto px-6 md:px-10">',
  '        <div className="text-center mb-16">',
  '          <p className="font-inter text-xs text-forest tracking-[0.35em] uppercase mb-3">O que oferecemos</p>',
  '          <h2 className="font-raleway font-black text-4xl md:text-5xl text-ink mb-4">Nossos Servi\u00e7os</h2>',
  '          <GoldDivider icon="scissor" className="max-w-xs mx-auto"/>',
  '        </div>',
  '        <div ref={ref} className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">',
  '          {SERVICES.map((sv,i) => {',
  '            const Icon = ICONS[sv.icon] || Scissors',
  '            return (',
  '              <div key={sv.id} className="card-natural rounded-xl p-6 flex flex-col gap-4 relative"',
  '                style={{ opacity:isVisible?1:0, transform:isVisible?"none":"translateY(30px)", transition:`all 0.5s ease ${i*100}ms` }}>',
  '                {sv.featured && <span className="absolute top-4 right-4 bg-forest text-white text-[9px] font-raleway font-bold px-2 py-1 tracking-wider rounded">POPULAR</span>}',
  '                {sv.premium && <span className="absolute top-4 right-4 border border-olive text-olive text-[9px] font-raleway font-bold px-2 py-1 tracking-wider rounded">PREMIUM</span>}',
  '                <div className="w-12 h-12 rounded-full bg-forest/8 border border-forest/15 flex items-center justify-center">',
  '                  <Icon size={20} className="text-forest"/>',
  '                </div>',
  '                <div className="flex-1">',
  '                  <h3 className="font-raleway text-ink font-bold text-base tracking-wide mb-2">{sv.name}</h3>',
  '                  <p className="font-inter text-sm text-ink-muted leading-relaxed">{sv.description}</p>',
  '                </div>',
  '                <div className="flex items-end justify-between border-t border-natural-border pt-4 mt-auto">',
  '                  <span className="font-raleway text-2xl font-black text-forest">R${sv.price}</span>',
  '                  <span className="font-inter text-xs text-ink-dim">{sv.duration}</span>',
  '                </div>',
  '                <Button href={BUSINESS.inbarberUrl} target="_blank" variant="outline" size="sm" className="w-full">AGENDAR</Button>',
  '              </div>',
  '            )',
  '          })}',
  '        </div>',
  '      </div>',
  '    </section>',
  '  )',
  '}',
].join('\n')

// ─── VideoSection ─────────────────────────────────────────────────────────────
const video = [
  'import { Play } from "lucide-react"',
  'import { GoldDivider } from "@/components/ui/GoldDivider"',
  'import { useScrollAnimation } from "@/hooks/useScrollAnimation"',
  'export function VideoSection() {',
  '  const { ref, isVisible } = useScrollAnimation(0.2)',
  '  return (',
  '    <section className="section-padding bg-natural-alt">',
  '      <div className="max-w-5xl mx-auto px-6 md:px-10">',
  '        <div className="text-center mb-12">',
  '          <p className="font-inter text-xs text-forest tracking-[0.35em] uppercase mb-3">Conhe\u00e7a o Ambiente</p>',
  '          <h2 className="font-raleway font-black text-4xl md:text-5xl text-ink mb-4">O Espa\u00e7o em V\u00eddeo</h2>',
  '          <GoldDivider className="max-w-xs mx-auto"/>',
  '        </div>',
  '        <div ref={ref} className="relative rounded-2xl overflow-hidden shadow-[0_8px_60px_rgba(61,90,61,0.15)] border border-natural-border transition-all duration-700"',
  '          style={{ opacity:isVisible?1:0, transform:isVisible?"none":"scale(0.97)" }}>',
  '          <div className="aspect-video">',
  '            <video className="w-full h-full object-cover" controls preload="metadata" poster="/assets/images/video-thumb.jpg">',
  '              <source src="/assets/videos/ambiente.mp4" type="video/mp4"/>',
  '            </video>',
  '            <div className="absolute inset-0 video-placeholder flex flex-col items-center justify-center gap-6" id="vph">',
  '              <div className="w-20 h-20 rounded-full border-2 border-white/30 flex items-center justify-center bg-white/10 backdrop-blur-sm">',
  '                <Play size={32} className="text-white ml-1"/>',
  '              </div>',
  '              <div className="text-center">',
  '                <p className="font-raleway text-white font-bold text-sm tracking-widest mb-1">AMBIENTE BARBEZA</p>',
  '                <p className="font-inter text-white/40 text-xs">V\u00eddeo em breve</p>',
  '              </div>',
  '            </div>',
  '          </div>',
  '        </div>',
  '      </div>',
  '    </section>',
  '  )',
  '}',
].join('\n')

// ─── SpaceSection ─────────────────────────────────────────────────────────────
const space = [
  'import { useState } from "react"',
  'import { SPACE_ROOMS, BUSINESS } from "@/data/content"',
  'import { Button } from "@/components/ui/Button"',
  'import { GoldDivider } from "@/components/ui/GoldDivider"',
  'import { useScrollAnimation } from "@/hooks/useScrollAnimation"',
  'export function SpaceSection() {',
  '  const [active, setActive] = useState(0)',
  '  const { ref, isVisible } = useScrollAnimation(0.1)',
  '  const room = SPACE_ROOMS[active]',
  '  return (',
  '    <section id="espaco" className="section-padding bg-white">',
  '      <div className="max-w-7xl mx-auto px-6 md:px-10">',
  '        <div className="text-center mb-14">',
  '          <p className="font-inter text-xs text-forest tracking-[0.35em] uppercase mb-3">Nosso Espa\u00e7o</p>',
  '          <h2 className="font-raleway font-black text-4xl md:text-5xl text-ink mb-4">O Ambiente</h2>',
  '          <GoldDivider className="max-w-xs mx-auto"/>',
  '        </div>',
  '        <div ref={ref} className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-center"',
  '          style={{ opacity:isVisible?1:0, transition:"opacity 0.7s ease" }}>',
  '          <div className="relative rounded-2xl overflow-hidden aspect-[4/3] shadow-[0_8px_40px_rgba(61,90,61,0.12)]">',
  '            <img src={room.image} alt={room.label}',
  '              className="w-full h-full object-cover transition-all duration-700"',
  '              onError={(e) => { (e.target as HTMLImageElement).style.opacity="0" }}/>',
  '            <div className="absolute inset-0 flex items-center justify-center">',
  '              <div className="text-center p-8">',
  '                <div className="w-16 h-16 rounded-full bg-forest/10 border border-forest/20 flex items-center justify-center mx-auto mb-4">',
  '                  <svg viewBox="0 0 24 24" className="w-8 h-8 text-forest" fill="none" stroke="currentColor" strokeWidth="1.5">',
  '                    <path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"/>',
  '                    <polyline points="9 22 9 12 15 12 15 22"/>',
  '                  </svg>',
  '                </div>',
  '                <p className="font-raleway text-ink font-bold text-sm tracking-widest">{room.label}</p>',
  '                <p className="font-inter text-ink-dim text-xs mt-1">Imagem em breve</p>',
  '              </div>',
  '            </div>',
  '            <div className="absolute top-4 left-4">',
  '              <span className="bg-forest text-white text-[9px] font-raleway font-bold px-3 py-1 tracking-widest rounded">{room.badge}</span>',
  '            </div>',
  '          </div>',
  '          <div className="flex flex-col gap-6">',
  '            <div className="flex gap-3 flex-wrap">',
  '              {SPACE_ROOMS.map((r,i) => (',
  '                <button key={r.id} onClick={() => setActive(i)}',
  '                  className={`font-inter text-xs tracking-wider px-4 py-2 rounded-full border transition-all duration-200 ${',
  '                    i === active',
  '                      ? "bg-forest text-white border-forest"',
  '                      : "border-natural-border text-ink-muted hover:border-forest hover:text-forest"',
  '                  }`}>{r.label}</button>',
  '              ))}',
  '            </div>',
  '            <div>',
  '              <h3 className="font-raleway text-3xl font-black text-ink mb-4">{room.label}</h3>',
  '              <p className="font-inter text-ink-muted leading-relaxed">{room.description}</p>',
  '            </div>',
  '            <div className="pt-2">',
  '              <Button href={BUSINESS.inbarberUrl} target="_blank" size="lg">AGENDAR VISITA</Button>',
  '            </div>',
  '          </div>',
  '        </div>',
  '      </div>',
  '    </section>',
  '  )',
  '}',
].join('\n')

// ─── GallerySection ───────────────────────────────────────────────────────────
const gallery = [
  'import { useState } from "react"',
  'import { GALLERY } from "@/data/content"',
  'import { GoldDivider } from "@/components/ui/GoldDivider"',
  'import { useScrollAnimation } from "@/hooks/useScrollAnimation"',
  'const CATS = [',
  '  { key: "all",     label: "Todos"    },',
  '  { key: "cortes",  label: "Cortes"   },',
  '  { key: "barbas",  label: "Barbas"   },',
  '  { key: "ambiente",label: "Ambiente" },',
  ']',
  'export function GallerySection() {',
  '  const [cat, setCat] = useState("all")',
  '  const { ref, isVisible } = useScrollAnimation(0.1)',
  '  const filtered = cat === "all" ? GALLERY : GALLERY.filter(g => g.category === cat)',
  '  return (',
  '    <section id="galeria" className="section-padding bg-natural">',
  '      <div className="max-w-7xl mx-auto px-6 md:px-10">',
  '        <div className="text-center mb-12">',
  '          <p className="font-inter text-xs text-forest tracking-[0.35em] uppercase mb-3">Nosso trabalho</p>',
  '          <h2 className="font-raleway font-black text-4xl md:text-5xl text-ink mb-4">Galeria</h2>',
  '          <GoldDivider className="max-w-xs mx-auto"/>',
  '        </div>',
  '        <div className="flex items-center justify-center gap-3 flex-wrap mb-10">',
  '          {CATS.map(c => (',
  '            <button key={c.key} onClick={() => setCat(c.key)}',
  '              className={`font-inter text-xs tracking-wider px-5 py-2 rounded-full border transition-all duration-200 ${',
  '                c.key === cat',
  '                  ? "bg-forest text-white border-forest"',
  '                  : "border-natural-border text-ink-muted hover:border-forest hover:text-forest"',
  '              }`}>{c.label}</button>',
  '          ))}',
  '        </div>',
  '        <div ref={ref} className="grid grid-cols-2 md:grid-cols-3 gap-4">',
  '          {filtered.map((item, i) => (',
  '            <div key={item.id} className="relative aspect-square rounded-xl overflow-hidden group cursor-pointer"',
  '              style={{ opacity:isVisible?1:0, transform:isVisible?"none":"scale(0.95)", transition:`all 0.5s ease ${i*80}ms` }}>',
  '              <img src={item.file} alt={item.alt}',
  '                className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"',
  '                onError={(e) => { (e.target as HTMLImageElement).style.display="none" }}/>',
  '              <div className="absolute inset-0 bg-forest-deep flex items-center justify-center">',
  '                <div className="text-center p-4">',
  '                  <div className="w-10 h-10 rounded-full bg-forest/20 border border-forest/30 flex items-center justify-center mx-auto mb-2">',
  '                    <svg viewBox="0 0 24 24" className="w-5 h-5 text-white/60" fill="none" stroke="currentColor" strokeWidth="1.5">',
  '                      <rect x="3" y="3" width="18" height="18" rx="2"/>',
  '                      <circle cx="8.5" cy="8.5" r="1.5"/>',
  '                      <polyline points="21 15 16 10 5 21"/>',
  '                    </svg>',
  '                  </div>',
  '                  <p className="font-inter text-white/50 text-[10px]">{item.alt}</p>',
  '                </div>',
  '              </div>',
  '              <div className="absolute inset-0 bg-gradient-to-t from-forest-deep/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-4">',
  '                <p className="font-inter text-white text-xs font-medium">{item.alt}</p>',
  '              </div>',
  '            </div>',
  '          ))}',
  '        </div>',
  '      </div>',
  '    </section>',
  '  )',
  '}',
].join('\n')

// ─── BookingSection ───────────────────────────────────────────────────────────
const booking = [
  'import { useState } from "react"',
  'import { Phone, MessageCircle, Calendar } from "lucide-react"',
  'import { BUSINESS } from "@/data/content"',
  'import { Button } from "@/components/ui/Button"',
  'import { GoldDivider } from "@/components/ui/GoldDivider"',
  'import { useScrollAnimation } from "@/hooks/useScrollAnimation"',
  'export function BookingSection() {',
  '  const { ref, isVisible } = useScrollAnimation(0.1)',
  '  const [iframeLoaded, setIframeLoaded] = useState(false)',
  '  return (',
  '    <section id="agendamento" className="section-padding bg-natural-alt">',
  '      <div className="max-w-7xl mx-auto px-6 md:px-10">',
  '        <div className="text-center mb-12">',
  '          <p className="font-inter text-xs text-forest tracking-[0.35em] uppercase mb-3">Reserve seu hor\u00e1rio</p>',
  '          <h2 className="font-raleway font-black text-4xl md:text-5xl text-ink mb-4">Agendamento</h2>',
  '          <GoldDivider className="max-w-xs mx-auto"/>',
  '        </div>',
  '        <div ref={ref} className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-start"',
  '          style={{ opacity:isVisible?1:0, transition:"opacity 0.7s ease" }}>',
  '          <div className="flex flex-col gap-6">',
  '            <div className="card-natural rounded-2xl p-7">',
  '              <h3 className="font-raleway text-ink font-black text-xl mb-5 tracking-wide">Reserve seu Hor\u00e1rio</h3>',
  '              <div className="space-y-4">',
  '                <a href={`https://wa.me/${BUSINESS.whatsapp}`} target="_blank" rel="noopener noreferrer"',
  '                  className="flex items-center gap-4 p-4 rounded-xl border border-natural-border hover:border-forest hover:bg-forest/5 transition-all duration-200 group">',
  '                  <div className="w-10 h-10 rounded-full bg-green-50 border border-green-200 flex items-center justify-center group-hover:bg-green-100 transition-colors">',
  '                    <MessageCircle size={18} className="text-green-600"/>',
  '                  </div>',
  '                  <div>',
  '                    <p className="font-raleway text-sm font-bold text-ink">WhatsApp</p>',
  '                    <p className="font-inter text-xs text-ink-muted">{BUSINESS.phone}</p>',
  '                  </div>',
  '                </a>',
  '                <a href={BUSINESS.inbarberUrl} target="_blank" rel="noopener noreferrer"',
  '                  className="flex items-center gap-4 p-4 rounded-xl border border-natural-border hover:border-forest hover:bg-forest/5 transition-all duration-200 group">',
  '                  <div className="w-10 h-10 rounded-full bg-forest/8 border border-forest/20 flex items-center justify-center group-hover:bg-forest/15 transition-colors">',
  '                    <Calendar size={18} className="text-forest"/>',
  '                  </div>',
  '                  <div>',
  '                    <p className="font-raleway text-sm font-bold text-ink">InBarber App</p>',
  '                    <p className="font-inter text-xs text-ink-muted">Agendamento online</p>',
  '                  </div>',
  '                </a>',
  '                <a href={`tel:${BUSINESS.phone}`}',
  '                  className="flex items-center gap-4 p-4 rounded-xl border border-natural-border hover:border-forest hover:bg-forest/5 transition-all duration-200 group">',
  '                  <div className="w-10 h-10 rounded-full bg-forest/8 border border-forest/20 flex items-center justify-center group-hover:bg-forest/15 transition-colors">',
  '                    <Phone size={18} className="text-forest"/>',
  '                  </div>',
  '                  <div>',
  '                    <p className="font-raleway text-sm font-bold text-ink">Ligar</p>',
  '                    <p className="font-inter text-xs text-ink-muted">{BUSINESS.phone}</p>',
  '                  </div>',
  '                </a>',
  '              </div>',
  '            </div>',
  '            <div className="hidden md:block">',
  '              <Button href={BUSINESS.inbarberUrl} target="_blank" size="lg" className="w-full">ABRIR AGENDA ONLINE</Button>',
  '            </div>',
  '          </div>',
  '          <div className="card-natural rounded-2xl overflow-hidden shadow-[0_4px_30px_rgba(61,90,61,0.08)]">',
  '            <div className="bg-forest px-5 py-3 flex items-center gap-2">',
  '              <div className="flex gap-1.5">',
  '                <div className="w-3 h-3 rounded-full bg-white/20"/>',
  '                <div className="w-3 h-3 rounded-full bg-white/20"/>',
  '                <div className="w-3 h-3 rounded-full bg-white/20"/>',
  '              </div>',
  '              <p className="font-inter text-white/70 text-xs ml-2">Agenda Barbeza \u2014 InBarber</p>',
  '            </div>',
  '            <div className="relative" style={{ height: "520px" }}>',
  '              {!iframeLoaded && (',
  '                <div className="absolute inset-0 flex flex-col items-center justify-center bg-natural gap-4">',
  '                  <div className="w-12 h-12 rounded-full border-2 border-forest/20 border-t-forest animate-spin"/>',
  '                  <p className="font-inter text-ink-muted text-sm">Carregando agenda...</p>',
  '                </div>',
  '              )}',
  '              <iframe',
  '                src={BUSINESS.inbarberUrl}',
  '                className="w-full h-full border-0"',
  '                title="Agendamento InBarber"',
  '                onLoad={() => setIframeLoaded(true)}',
  '                allow="payment"',
  '                sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-top-navigation"',
  '              />',
  '            </div>',
  '            <div className="px-5 py-3 bg-natural border-t border-natural-border md:hidden">',
  '              <Button href={BUSINESS.inbarberUrl} target="_blank" size="sm" className="w-full">ABRIR NO APP</Button>',
  '            </div>',
  '          </div>',
  '        </div>',
  '      </div>',
  '    </section>',
  '  )',
  '}',
].join('\n')

// ─── LocationSection ──────────────────────────────────────────────────────────
const location = [
  'import { MapPin, Clock, Phone, Instagram, MessageCircle } from "lucide-react"',
  'import { BUSINESS, HOURS } from "@/data/content"',
  'import { Button } from "@/components/ui/Button"',
  'import { GoldDivider } from "@/components/ui/GoldDivider"',
  'import { useScrollAnimation } from "@/hooks/useScrollAnimation"',
  'export function LocationSection() {',
  '  const { ref, isVisible } = useScrollAnimation(0.1)',
  '  const activeHours = Object.values(HOURS).filter(h => h.active)',
  '  return (',
  '    <section id="contato" className="section-padding bg-natural">',
  '      <div className="max-w-7xl mx-auto px-6 md:px-10">',
  '        <div className="text-center mb-12">',
  '          <p className="font-inter text-xs text-forest tracking-[0.35em] uppercase mb-3">Como chegar</p>',
  '          <h2 className="font-raleway font-black text-4xl md:text-5xl text-ink mb-4">Localiza\u00e7\u00e3o</h2>',
  '          <GoldDivider className="max-w-xs mx-auto"/>',
  '        </div>',
  '        <div ref={ref} className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-start"',
  '          style={{ opacity:isVisible?1:0, transition:"opacity 0.7s ease" }}>',
  '          <div className="rounded-2xl overflow-hidden shadow-[0_8px_40px_rgba(61,90,61,0.12)] border border-natural-border aspect-[4/3]">',
  '            <iframe',
  '              src={BUSINESS.googleMapsUrl}',
  '              className="w-full h-full border-0"',
  '              title="Localiza\u00e7\u00e3o Barbeza"',
  '              loading="lazy"',
  '            />',
  '          </div>',
  '          <div className="flex flex-col gap-6">',
  '            <div className="card-natural rounded-2xl p-6">',
  '              <div className="flex items-start gap-4 mb-5">',
  '                <div className="w-10 h-10 rounded-full bg-forest/10 border border-forest/20 flex items-center justify-center shrink-0">',
  '                  <MapPin size={18} className="text-forest"/>',
  '                </div>',
  '                <div>',
  '                  <p className="font-raleway text-ink font-bold text-sm mb-1">Endere\u00e7o</p>',
  '                  <p className="font-inter text-ink-muted text-sm leading-relaxed">{BUSINESS.fullAddress}</p>',
  '                  <a href={BUSINESS.googleMapsLink} target="_blank" rel="noopener noreferrer"',
  '                    className="font-inter text-xs text-forest hover:underline mt-1 inline-block">Ver no Google Maps \u2192</a>',
  '                </div>',
  '              </div>',
  '              <div className="flex items-start gap-4">',
  '                <div className="w-10 h-10 rounded-full bg-forest/10 border border-forest/20 flex items-center justify-center shrink-0">',
  '                  <Clock size={18} className="text-forest"/>',
  '                </div>',
  '                <div className="flex-1">',
  '                  <p className="font-raleway text-ink font-bold text-sm mb-3">Hor\u00e1rio de Funcionamento</p>',
  '                  <div className="space-y-1.5">',
  '                    {activeHours.map(h => (',
  '                      <div key={h.label} className="flex items-center justify-between text-xs">',
  '                        <span className="font-inter text-ink-muted">{h.label}</span>',
  '                        <span className="font-raleway font-bold text-forest">{h.open} \u2013 {h.close}</span>',
  '                      </div>',
  '                    ))}',
  '                    <div className="flex items-center justify-between text-xs mt-2 pt-2 border-t border-natural-border">',
  '                      <span className="font-inter text-ink-muted">Domingo</span>',
  '                      <span className="font-inter text-ink-dim">Fechado</span>',
  '                    </div>',
  '                  </div>',
  '                </div>',
  '              </div>',
  '            </div>',
  '            <div className="flex flex-col gap-3">',
  '              <a href={`https://wa.me/${BUSINESS.whatsapp}`} target="_blank" rel="noopener noreferrer">',
  '                <Button size="lg" className="w-full bg-green-600 hover:bg-green-700 border-0 text-white">',
  '                  <MessageCircle size={18} className="mr-2"/> WHATSAPP',
  '                </Button>',
  '              </a>',
  '              <div className="grid grid-cols-2 gap-3">',
  '                <a href={`tel:${BUSINESS.phone}`}>',
  '                  <Button variant="outline" size="sm" className="w-full"><Phone size={14} className="mr-2"/> Ligar</Button>',
  '                </a>',
  '                <a href={BUSINESS.instagramUrl} target="_blank" rel="noopener noreferrer">',
  '                  <Button variant="outline" size="sm" className="w-full"><Instagram size={14} className="mr-2"/> Instagram</Button>',
  '                </a>',
  '              </div>',
  '            </div>',
  '          </div>',
  '        </div>',
  '      </div>',
  '    </section>',
  '  )',
  '}',
].join('\n')

// ─── TestimonialsSection ──────────────────────────────────────────────────────
const testimonials = [
  'import { useState, useEffect, useRef } from "react"',
  'import { ChevronLeft, ChevronRight, Star } from "lucide-react"',
  'import { TESTIMONIALS } from "@/data/content"',
  'import { GoldDivider } from "@/components/ui/GoldDivider"',
  'import { useScrollAnimation } from "@/hooks/useScrollAnimation"',
  'export function TestimonialsSection() {',
  '  const [cur, setCur] = useState(0)',
  '  const { ref, isVisible } = useScrollAnimation(0.2)',
  '  const timer = useRef<ReturnType<typeof setInterval>>()',
  '  const next = () => setCur(c => (c+1)%TESTIMONIALS.length)',
  '  const prev = () => setCur(c => (c-1+TESTIMONIALS.length)%TESTIMONIALS.length)',
  '  useEffect(() => { timer.current = setInterval(next, 5000); return () => clearInterval(timer.current) }, [])',
  '  const t = TESTIMONIALS[cur]',
  '  return (',
  '    <section id="depoimentos" className="section-padding bg-forest-deep">',
  '      <div className="max-w-4xl mx-auto px-6 md:px-10">',
  '        <div className="text-center mb-14">',
  '          <p className="font-inter text-xs text-olive/80 tracking-[0.35em] uppercase mb-3">O que dizem</p>',
  '          <h2 className="font-raleway font-black text-4xl md:text-5xl text-white mb-4">Avalia\u00e7\u00f5es</h2>',
  '          <GoldDivider className="max-w-xs mx-auto" light={true}/>',
  '        </div>',
  '        <div ref={ref} style={{ opacity:isVisible?1:0, transition:"opacity 0.7s ease" }}>',
  '          <div className="glass-card-dark rounded-2xl p-8 md:p-12 text-center relative">',
  '            <div className="absolute top-6 left-8 text-white/5 font-playfair text-9xl leading-none select-none">"</div>',
  '            <div className="flex items-center justify-center gap-1 mb-6">',
  '              {Array.from({length:t.rating}).map((_,i) => <Star key={i} size={16} className="text-olive fill-olive"/>)}',
  '            </div>',
  '            <p className="font-playfair italic text-lg md:text-xl text-white/90 leading-relaxed mb-6 relative z-10">"{t.text}"</p>',
  '            <div className="flex flex-col items-center gap-1">',
  '              <p className="font-raleway text-olive-light text-sm tracking-widest font-bold">{t.name}</p>',
  '              {t.service && <p className="font-inter text-xs text-white/40">{t.service}</p>}',
  '            </div>',
  '          </div>',
  '          <div className="flex items-center justify-center gap-6 mt-8">',
  '            <button onClick={prev} className="w-10 h-10 rounded-full border border-white/20 flex items-center justify-center text-white/50 hover:border-olive hover:text-olive transition-all duration-200"><ChevronLeft size={18}/></button>',
  '            <div className="flex gap-2">',
  '              {TESTIMONIALS.map((_,i) => (',
  '                <button key={i} onClick={() => setCur(i)} className={`rounded-full transition-all duration-300 ${i===cur?"w-6 h-2 bg-olive":"w-2 h-2 bg-white/20"}`}/>',
  '              ))}',
  '            </div>',
  '            <button onClick={next} className="w-10 h-10 rounded-full border border-white/20 flex items-center justify-center text-white/50 hover:border-olive hover:text-olive transition-all duration-200"><ChevronRight size={18}/></button>',
  '          </div>',
  '        </div>',
  '      </div>',
  '    </section>',
  '  )',
  '}',
].join('\n')

// ─── Gravar arquivos ──────────────────────────────────────────────────────────
const write = (p, text) => {
  fs.mkdirSync(require('path').dirname(p), { recursive: true })
  fs.writeFileSync(p, text, { encoding: 'utf8' })
  console.log('OK:', p.split('/').slice(-1)[0])
}

// barbeza2
write(B2 + '/src/data/content.ts', content)
write(B2 + '/src/components/layout/Navbar.tsx', navbarB2)
write(B2 + '/src/components/landing/ServicesSection.tsx', services)
write(B2 + '/src/components/landing/VideoSection.tsx', video)
write(B2 + '/src/components/landing/SpaceSection.tsx', space)
write(B2 + '/src/components/landing/GallerySection.tsx', gallery)
write(B2 + '/src/components/landing/BookingSection.tsx', booking)
write(B2 + '/src/components/landing/LocationSection.tsx', location)
write(B2 + '/src/components/landing/TestimonialsSection.tsx', testimonials)

// barbeza-barbearia (mesmos fixes de encoding, sem mudar navbar dark)
write(B1 + '/src/data/content.ts', content)
write(B1 + '/src/components/landing/ServicesSection.tsx', services)
write(B1 + '/src/components/landing/VideoSection.tsx', video)
write(B1 + '/src/components/landing/SpaceSection.tsx', space)
write(B1 + '/src/components/landing/GallerySection.tsx', gallery)
write(B1 + '/src/components/landing/BookingSection.tsx', booking)
write(B1 + '/src/components/landing/LocationSection.tsx', location)
write(B1 + '/src/components/landing/TestimonialsSection.tsx', testimonials)

console.log('\nTudo gravado em UTF-8 sem BOM!')
