const fs = require('fs')

const B1 = 'C:/Users/Helbert/Documents/Verdent/barbeza-barbearia'

// HeroSection premium dark com logo grande + flash glow + entrada escalonada
const hero = [
  'import { useEffect, useRef, useState } from "react"',
  'import { BUSINESS } from "@/data/content"',
  'import { Button } from "@/components/ui/Button"',
  'import { ChevronDown } from "lucide-react"',
  '',
  'export function HeroSection() {',
  '  const videoRef = useRef<HTMLVideoElement>(null)',
  '  const [videoLoaded, setVideoLoaded] = useState(false)',
  '  const [phase, setPhase] = useState(0)',
  '',
  '  useEffect(() => {',
  '    videoRef.current?.play().catch(() => {})',
  '    const t1 = setTimeout(() => setPhase(1), 200)',
  '    const t2 = setTimeout(() => setPhase(2), 900)',
  '    const t3 = setTimeout(() => setPhase(3), 1300)',
  '    const t4 = setTimeout(() => setPhase(4), 1700)',
  '    return () => [t1, t2, t3, t4].forEach(clearTimeout)',
  '  }, [])',
  '',
  '  return (',
  '    <section id="hero" className="relative min-h-screen flex items-center justify-center overflow-hidden">',
  '',
  '      {/* ── Background ── */}',
  '      <div className="absolute inset-0 video-placeholder">',
  '        <img',
  '          src="/assets/images/hero-bg.jpg"',
  '          alt=""',
  '          className="absolute inset-0 w-full h-full object-cover opacity-40"',
  '          loading="eager"',
  '          onError={(e) => { (e.target as HTMLImageElement).src = "/assets/images/hero-bg.gif" }}',
  '        />',
  '        <video',
  '          ref={videoRef}',
  '          className={`absolute inset-0 w-full h-full object-cover transition-opacity duration-1000 ${videoLoaded ? "opacity-60" : "opacity-0"}`}',
  '          autoPlay muted loop playsInline preload="metadata"',
  '          onLoadedData={() => setVideoLoaded(true)}',
  '        >',
  '          <source src="/assets/videos/ambiente.mp4" type="video/mp4" />',
  '        </video>',
  '      </div>',
  '',
  '      {/* ── Overlays ── */}',
  '      <div className="absolute inset-0 bg-gradient-to-b from-dark/70 via-dark/50 to-dark/95" />',
  '      <div className="absolute inset-0 bg-gradient-to-r from-dark/60 to-transparent" />',
  '      <div className="absolute left-0 top-0 bottom-0 w-[2px] bg-brand opacity-60" />',
  '',
  '      {/* ── Partículas ── */}',
  '      <div className="absolute inset-0 pointer-events-none overflow-hidden">',
  '        {[',
  '          {top:"15%",left:"8%",  size:3, delay:"0s",   dur:"4s"  },',
  '          {top:"25%",left:"88%", size:2, delay:"0.8s", dur:"5s"  },',
  '          {top:"70%",left:"12%", size:2, delay:"1.5s", dur:"6s"  },',
  '          {top:"60%",left:"82%", size:4, delay:"0.3s", dur:"4.5s"},',
  '          {top:"40%",left:"50%", size:2, delay:"2s",   dur:"7s"  },',
  '          {top:"80%",left:"60%", size:3, delay:"1s",   dur:"5.5s"},',
  '        ].map((p,i) => (',
  '          <div key={i} className="absolute rounded-full"',
  '            style={{',
  '              top: p.top, left: p.left,',
  '              width: p.size, height: p.size,',
  '              background: "rgba(139,133,85,0.5)",',
  '              animation: `particleFloat ${p.dur} ease-in-out ${p.delay} infinite`,',
  '            }}',
  '          />',
  '        ))}',
  '      </div>',
  '',
  '      {/* ── Conteúdo ── */}',
  '      <div className="relative z-10 text-center px-6 max-w-4xl mx-auto flex flex-col items-center">',
  '',
  '        {/* LOGO — grande com glow dourado */}',
  '        <div',
  '          className="mb-8 relative"',
  '          style={{',
  '            opacity: phase >= 1 ? 1 : 0,',
  '            transform: phase >= 1 ? "scale(1) translateY(0)" : "scale(0.82) translateY(-20px)",',
  '            transition: "opacity 0.8s cubic-bezier(.16,1,.3,1), transform 0.8s cubic-bezier(.16,1,.3,1)",',
  '          }}',
  '        >',
  '          {/* halo pulsante */}',
  '          <div',
  '            className="absolute inset-0 -m-6 rounded-full pointer-events-none"',
  '            style={{',
  '              background: "radial-gradient(ellipse at center, rgba(139,133,85,0.22) 0%, transparent 70%)",',
  '              animation: phase >= 1 ? "haloglow 3s ease-in-out infinite" : "none",',
  '            }}',
  '          />',
  '          {/* flash na entrada */}',
  '          {phase >= 1 && (',
  '            <div',
  '              className="absolute inset-0 -m-8 rounded-full pointer-events-none"',
  '              style={{',
  '                background: "radial-gradient(ellipse at center, rgba(255,255,255,0.18) 0%, transparent 65%)",',
  '                animation: "flashOnce 1.2s ease-out forwards",',
  '              }}',
  '            />',
  '          )}',
  '          <img',
  '            src="/assets/logo/logo-horizontal-branca.png"',
  '            alt="Barbeza Barbearia"',
  '            className="relative w-auto object-contain"',
  '            style={{',
  '              height: "clamp(90px, 14vw, 160px)",',
  '              filter: "drop-shadow(0 6px 32px rgba(139,133,85,0.7)) drop-shadow(0 0 60px rgba(139,133,85,0.3))",',
  '            }}',
  '          />',
  '        </div>',
  '',
  '        {/* linha divisória */}',
  '        <div',
  '          className="flex items-center gap-4 mb-6 w-full max-w-xs"',
  '          style={{',
  '            opacity: phase >= 2 ? 1 : 0,',
  '            transform: phase >= 2 ? "scaleX(1)" : "scaleX(0.3)",',
  '            transition: "opacity 0.6s ease, transform 0.6s ease",',
  '          }}',
  '        >',
  '          <div className="flex-1 h-px bg-gradient-to-r from-transparent to-brand/60" />',
  '          <div className="w-1.5 h-1.5 rounded-full bg-brand/80" />',
  '          <div className="flex-1 h-px bg-gradient-to-l from-transparent to-brand/60" />',
  '        </div>',
  '',
  '        {/* Tagline */}',
  '        <div',
  '          className="mb-4"',
  '          style={{',
  '            opacity: phase >= 2 ? 1 : 0,',
  '            transform: phase >= 2 ? "none" : "translateY(12px)",',
  '            transition: "opacity 0.6s ease, transform 0.6s ease",',
  '          }}',
  '        >',
  '          <span className="font-inter text-[11px] text-brand tracking-[0.45em] uppercase">',
  '            {BUSINESS.tagline}',
  '          </span>',
  '        </div>',
  '',
  '        {/* Slogan */}',
  '        <div',
  '          className="mb-10"',
  '          style={{',
  '            opacity: phase >= 3 ? 1 : 0,',
  '            transform: phase >= 3 ? "none" : "translateY(16px)",',
  '            transition: "opacity 0.7s ease, transform 0.7s ease",',
  '          }}',
  '        >',
  '          <p className="font-playfair italic text-xl sm:text-2xl md:text-3xl text-cream-muted tracking-wide">',
  '            {BUSINESS.slogan}',
  '          </p>',
  '        </div>',
  '',
  '        {/* CTAs */}',
  '        <div',
  '          className="flex flex-col sm:flex-row items-center justify-center gap-4"',
  '          style={{',
  '            opacity: phase >= 4 ? 1 : 0,',
  '            transform: phase >= 4 ? "none" : "translateY(20px)",',
  '            transition: "opacity 0.7s ease, transform 0.7s ease",',
  '          }}',
  '        >',
  '          <Button href={BUSINESS.inbarberUrl} target="_blank" size="lg" variant="gold">',
  '            AGENDAR HOR\u00c1RIO',
  '          </Button>',
  '          <Button href="#espaco" size="lg" variant="outline">',
  '            CONHECER O ESPA\u00c7O',
  '          </Button>',
  '        </div>',
  '',
  '        <div',
  '          className="mt-6"',
  '          style={{',
  '            opacity: phase >= 4 ? 0.55 : 0,',
  '            transition: "opacity 1s ease 0.4s",',
  '          }}',
  '        >',
  '          <span className="font-inter text-xs text-cream-muted tracking-widest">',
  '            Beth\u00e2nia, Ipatinga \u2014 MG',
  '          </span>',
  '        </div>',
  '      </div>',
  '',
  '      <a',
  '        href="#stats"',
  '        className="absolute bottom-8 left-1/2 -translate-x-1/2 text-brand/60 hover:text-brand transition-colors"',
  '        style={{ animation: "bounce 2s ease-in-out infinite" }}',
  '        aria-label="Rolar para baixo"',
  '      >',
  '        <ChevronDown size={28} />',
  '      </a>',
  '',
  '      {/* decorativos de canto */}',
  '      <div className="absolute top-20 right-8 hidden lg:block opacity-15">',
  '        <svg width="80" height="80" viewBox="0 0 80 80" fill="none"><rect x="0" y="0" width="1" height="80" fill="#8B8555"/><rect x="0" y="0" width="80" height="1" fill="#8B8555"/></svg>',
  '      </div>',
  '      <div className="absolute bottom-20 left-8 hidden lg:block opacity-15">',
  '        <svg width="80" height="80" viewBox="0 0 80 80" fill="none"><rect x="79" y="0" width="1" height="80" fill="#8B8555"/><rect x="0" y="79" width="80" height="1" fill="#8B8555"/></svg>',
  '      </div>',
  '',
  '      <style>{`',
  '        @keyframes haloglow {',
  '          0%,100% { opacity: 0.6; transform: scale(1); }',
  '          50%      { opacity: 1;   transform: scale(1.12); }',
  '        }',
  '        @keyframes flashOnce {',
  '          0%   { opacity: 1; transform: scale(0.8); }',
  '          40%  { opacity: 0.9; transform: scale(1.15); }',
  '          100% { opacity: 0; transform: scale(1.5); }',
  '        }',
  '        @keyframes particleFloat {',
  '          0%,100% { opacity:0; transform: translateY(0) scale(1); }',
  '          20%      { opacity:0.8; }',
  '          50%      { opacity:0.4; transform: translateY(-18px) scale(1.4); }',
  '          80%      { opacity:0.7; }',
  '        }',
  '        @keyframes bounce {',
  '          0%,100% { transform: translateX(-50%) translateY(0); }',
  '          50%      { transform: translateX(-50%) translateY(8px); }',
  '        }',
  '      `}</style>',
  '    </section>',
  '  )',
  '}',
].join('\n')

fs.writeFileSync(B1 + '/src/components/landing/HeroSection.tsx', hero, { encoding: 'utf8' })
console.log('HeroSection barbeza-barbearia atualizado!')
